data:
  db_path: 'src/data/market_data.db'
  table_name: 'mini_dolar'
  interval: '1min'

backtest:
  start_date: '2024-01-01'
  end_date: '2024-03-31'

strategy:
  lookback_period: 20
  atr_period: 14
  risk_free_rate: 0.05
  initial_capital: 100000
  max_risk_per_trade: 0.005
  performance_window: 20
  volume_window: 20
  high_volume_threshold: 1.5
  signal_threshold: 0.6
  high_vol_threshold: 0.7
  low_vol_threshold: 0.5
  
  feature_engineering:
    technical_indicators:
      - rsi
      - macd
      - bollinger
    price_features:
      - returns
      - volatility
    volume_features:
      - vwap
      - volume_profile
  
  ml_model:
    ensemble:
      models:
        - random_forest
        - gradient_boost
      weights:
        random_forest: 0.5
        gradient_boost: 0.5