backtest:
  commission_per_contract: 2.5
  end_date: '2024-06-30 23:59:59'
  initial_capital: 100000
  margin_requirement: 10000
  slippage_ticks: 1
  start_date: '2024-06-01 00:00:00'
data:
  db_path: src/data/candles.db
  interval: 1min
  table_name: candles
feature_engineering:
  adx_period: 14
  atr_smoothing: 14
  bb_period: 20
  bb_std: 2
  min_volume_ratio: 1.2
  momentum_periods:
  - 5
  - 10
  roc_periods:
  - 5
  - 10
  - 20
  rsi_period: 14
  sma_periods:
  - 20
  - 50
  volume_correlation_period: 10
  volume_ma_periods:
  - 5
  - 10
  - 20
ml_model:
  cross_validation_splits: 5
  max_depth: 8
  min_samples_leaf: 200
  n_estimators: 100
  probability_threshold: 0.6
  random_state: 42
  train_size: 0.8
  validation_size: 0.1
position_sizing:
  max_position_size: 5
  min_spacing_bars: 30
  position_size_atr_multiple: 1.5
stop_loss:
  atr_multiple: 1.5
  breakeven_level: 1.0
  trailing_stop: true
strategy:
  atr_period: 14
  initial_capital: 100000
  lookback_period: 20
  max_risk_per_trade: 0.005
  risk_free_rate: 0.05
  signal_threshold: 0.6
  signal_weights:
    ml_weight: 0.4
    traditional_weight: 0.6
take_profit:
  partial_exit_level: 1.5
  partial_exit_size: 0.5
  target_multiple: 2
